### ISSUE TITLE
Week 10 Deliverables

### ISSUE THREAD

**Issue by kangyeelim** [AY1920S1-CS2103T-T13-3/main#117]
- [x] Improve exception handling

- [x] JUnit testing

- [x] Complete Javadocs

- [x] CSS

- [x] Reduce coupling to improve code (try to only rely on Logic)

- [x] Brainstorm on how to improve the user interface

**Comment by CoderStellaJ** [comment]
Is this considered as done?

**Comment by kangyeelim** [comment]
Yes I do think so
