### ISSUE TITLE
Week 7 Deliverables

### ISSUE THREAD

**Issue by dawo5010** [AY1920S1-CS2103T-T13-3/main#17]
1. Update Project Website
- [x] AboutUs
- [x] ContactUs
- [x] README

2. Update User Guide
- [x] Into Project Webpage

3. Update Developer Guide
- [x] Target User Profile
- [x] Value Proposition
- [x] User Stories
- [x] Use Cases
- [x] Non-Functional Requirements
- [x] Glossary

**Comment by CoderStellaJ** [comment]
Well done!
